@extends('layouts.app')
@section('title', 'นักเรียนของฉัน')
@section('content')
<h1 class="page-title mb-1"><i class="bi bi-people"></i> นักเรียนของฉัน</h1><p class="text-muted small mb-3">ข้อมูลสำหรับเตรียมบทเรียนและติดตามความก้าวหน้า</p>
<form class="mb-3"><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input class="form-control" name="q" value="{{ $search }}" placeholder="ค้นหาชื่อนักเรียนหรือคอร์ส"><button class="btn btn-outline-secondary">ค้นหา</button></div></form>
<div class="row g-3">@forelse($enrollments as $e) @php $last=$lastSchedules->get($e->id);$next=$nextSchedules->get($e->id);$total=$e->course->total_sessions;$progress=$total?min(100,round($e->sessions_used/$total*100)):null; @endphp
<div class="col-md-6 col-xl-4"><div class="card h-100" style="border-radius:15px"><div class="card-body"><div class="d-flex gap-3"><div class="rounded-circle d-flex align-items-center justify-content-center flex-shrink-0" style="width:44px;height:44px;background:var(--accent-soft);color:var(--accent);font-weight:700">{{ mb_substr($e->student->nickname?:$e->student->full_name,0,1) }}</div><div><h6 class="fw-bold mb-0">{{ $e->student->full_name }}</h6><div class="small text-muted">{{ $e->student->student_code }} · {{ $e->course->name??'-' }}</div></div></div><hr>
<div class="small d-grid gap-2"><div class="d-flex justify-content-between"><span class="text-muted">คาบคงเหลือ</span><strong>{{ $e->remainingSessions()??'ไม่จำกัด' }}</strong></div><div class="d-flex justify-content-between"><span class="text-muted">ความก้าวหน้า</span><strong>{{ $progress!==null?$progress.'%':'เรียนต่อเนื่อง' }}</strong></div>@if($progress!==null)<div class="progress" style="height:5px"><div class="progress-bar" style="width:{{ $progress }}%"></div></div>@endif<div class="d-flex justify-content-between"><span class="text-muted">ผลประเมินล่าสุด</span><strong>{{ $e->courseEvaluation?$e->courseEvaluation->averageScore().'/5':'ยังไม่มี' }}</strong></div><div class="d-flex justify-content-between"><span class="text-muted">เรียนล่าสุด</span><strong>{{ $last?->schedule_date->format('d/m/Y')??'-' }}</strong></div><div class="d-flex justify-content-between"><span class="text-muted">คาบถัดไป</span><strong>{{ $next?->schedule_date->format('d/m/Y')??'ยังไม่ได้นัด' }}</strong></div><div class="d-flex justify-content-between"><span class="text-muted">ประวัติการลา</span><strong>{{ $e->leaves_count }} ครั้ง</strong></div></div><a href="{{ route('teacher.students.show',$e->student) }}" class="btn btn-sm btn-outline-secondary w-100 mt-3">ดูรายละเอียด</a></div></div></div>
@empty<div class="col-12"><div class="card"><div class="card-body text-center text-muted py-5">ไม่พบนักเรียนที่กำลังเรียนกับคุณ</div></div></div>@endforelse</div><div class="mt-3">{{ $enrollments->links() }}</div>
@endsection
