@extends('layouts.app')
@section('title', 'งานที่ต้องทำ')
@section('content')
@php $total=$attendanceTasks->count()+$reportTasks->count()+$homeworkTasks->count()+$makeupTasks->count()+$trialTasks->count(); @endphp
<h1 class="page-title mb-1"><i class="bi bi-list-check"></i> งานที่ต้องทำ</h1>
<p class="text-muted small mb-3">รวมงานค้างของคุณไว้ในหน้าเดียว · {{ $total }} รายการ</p>
<div class="row g-2 mb-3">
@foreach([['เช็กชื่อ/ยืนยันเวลา',$attendanceTasks->count(),'calendar-check'],['บันทึกผลการสอน',$reportTasks->count(),'journal-text'],['การบ้านรอตรวจ',$homeworkTasks->count(),'pencil-square'],['ชดเชยรออนุมัติ',$makeupTasks->count(),'arrow-repeat'],['นัดทดลองรอดำเนินการ',$trialTasks->count(),'person-check']] as $s)
<div class="col-6 col-lg-3"><div class="card h-100" style="border-radius:14px"><div class="card-body"><i class="bi bi-{{ $s[2] }} text-muted"></i><div class="fs-4 fw-bold">{{ $s[1] }}</div><div class="small text-muted">{{ $s[0] }}</div></div></div></div>
@endforeach
</div>
@if(!$total)<div class="card"><div class="card-body text-center py-5"><i class="bi bi-check2-circle fs-1 text-success"></i><h5 class="mt-2">จัดการครบแล้ว</h5><p class="text-muted small mb-0">ยังไม่มีงานที่ต้องดำเนินการ</p></div></div>@endif
@if($attendanceTasks->count())<div class="card mb-3"><div class="card-body"><h6 class="fw-bold">รอเช็กชื่อหรือยืนยันเวลา</h6>@foreach($attendanceTasks as $x)<div class="d-flex justify-content-between align-items-center border-bottom py-2 small"><div><strong>{{ $x->enrollment->student->full_name??'-' }}</strong><div class="text-muted">{{ $x->schedule_date->format('d/m/Y') }} {{ substr($x->start_time,0,5) }} · {{ $x->enrollment->course->name??'-' }}</div></div><a href="{{ route('teaching-logs.show',$x) }}" class="btn btn-sm btn-outline-primary">ดำเนินการ</a></div>@endforeach</div></div>@endif
@if($reportTasks->count())<div class="card mb-3"><div class="card-body"><h6 class="fw-bold">รอบันทึกผลการสอน</h6>@foreach($reportTasks as $x)<div class="d-flex justify-content-between align-items-center border-bottom py-2 small"><div><strong>{{ $x->student->full_name??'-' }}</strong><div class="text-muted">{{ $x->classSchedule->schedule_date?->format('d/m/Y') }} · {{ $x->enrollment->course->name??'-' }}</div></div><a href="{{ route('teaching-logs.show',$x->classSchedule) }}" class="btn btn-sm btn-outline-primary">บันทึกผล</a></div>@endforeach</div></div>@endif
@if($homeworkTasks->count())<div class="card mb-3"><div class="card-body d-flex justify-content-between align-items-center"><div><strong>การบ้านรอตรวจ {{ $homeworkTasks->count() }} รายการ</strong><div class="small text-muted">นักเรียนส่งงานเข้ามาแล้ว</div></div><a href="{{ route('homework-submissions.index') }}" class="btn btn-sm btn-outline-primary">ตรวจการบ้าน</a></div></div>@endif
@if($makeupTasks->count())<div class="card mb-3"><div class="card-body d-flex justify-content-between align-items-center"><div><strong>คำขอสอนชดเชย {{ $makeupTasks->count() }} รายการ</strong><div class="small text-muted">รอการตอบรับจากคุณ</div></div><a href="{{ route('makeup-requests.my-index') }}" class="btn btn-sm btn-outline-primary">ตรวจสอบ</a></div></div>@endif
@if($trialTasks->count())<div class="card"><div class="card-body"><h6 class="fw-bold">นัดทดลองรอดำเนินการ</h6>@foreach($trialTasks as $x)<div class="d-flex justify-content-between align-items-center border-bottom py-2 small"><div><strong>{{ $x->student_name }}</strong><div class="text-muted">{{ $x->trial_date?->format('d/m/Y') ?? 'ยังไม่นัด' }} {{ $x->trial_start_time ? substr($x->trial_start_time,0,5) : '' }} · {{ $x->course->name ?? $x->interest ?? '-' }} · <span class="badge {{ $x->confirmationStatusBadgeClass() }}">{{ $x->confirmationStatusLabel() }}</span></div></div><a href="{{ route('trial-leads.my-show',$x) }}" class="btn btn-sm btn-outline-primary">ดำเนินการ</a></div>@endforeach</div></div>@endif
@endsection
