<style>
    .leave-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.85rem}.leave-field label{font-size:.76rem;font-weight:600;margin-bottom:.3rem}.leave-field.full{grid-column:1/-1}.leave-dropzone{position:relative;border:2px dashed var(--border,#e4e1dc);border-radius:13px;padding:1.1rem;text-align:center;background:var(--surface,#f7f6f4);cursor:pointer;transition:.15s}.leave-dropzone:hover,.leave-dropzone.dragover{border-color:var(--accent);background:var(--accent-soft)}.leave-dropzone input{position:absolute;width:1px;height:1px;opacity:0}.leave-file-list{display:flex;flex-wrap:wrap;gap:.4rem;margin-top:.55rem}.leave-file-chip{display:inline-flex;align-items:center;gap:.35rem;border:1px solid var(--border);border-radius:9px;background:#fff;padding:.35rem .55rem;font-size:.72rem}.leave-form-actions{display:flex;justify-content:flex-end;align-items:center;gap:.75rem;margin-top:1rem;padding-top:1rem;border-top:1px solid var(--border)}@media(max-width:575.98px){.leave-form-grid{grid-template-columns:1fr}.leave-field.full{grid-column:auto}.leave-form-actions{align-items:stretch;flex-direction:column}.leave-form-actions .btn{width:100%}}
</style>
<form action="{{ route('teachers.leaves.store', $teacher) }}" method="POST" enctype="multipart/form-data" class="teacher-leave-form">
    @csrf
    <div class="leave-form-grid">
        <div class="leave-field"><label>ตั้งแต่วันที่ <span class="text-danger">*</span></label><input type="date" name="leave_date_from" value="{{ old('leave_date_from') }}" class="form-control" required></div>
        <div class="leave-field"><label>ถึงวันที่ <span class="text-danger">*</span></label><input type="date" name="leave_date_to" value="{{ old('leave_date_to') }}" class="form-control" required></div>
        <div class="leave-field full"><label>เหตุผลการลา</label><textarea name="reason" class="form-control" rows="2" maxlength="500" placeholder="เช่น ลาป่วย ธุระส่วนตัว หรือเหตุผลอื่น ๆ">{{ old('reason') }}</textarea></div>
        <div class="leave-field full"><label>ไฟล์ประกอบ <span class="text-muted fw-normal">(ไม่บังคับ สูงสุด 5 ไฟล์)</span></label><label class="leave-dropzone"><input type="file" name="attachments[]" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.doc,.docx"><i class="bi bi-cloud-arrow-up fs-4 text-muted"></i><div class="fw-semibold small mt-1">คลิกเพื่อเลือกหรือลากไฟล์มาวาง</div><div class="text-muted" style="font-size:.7rem">รองรับรูปภาพ PDF และ Word · ไม่เกิน 10 MB ต่อไฟล์</div></label><div class="leave-file-list"></div></div>
    </div>
    <div class="leave-form-actions"><span class="text-muted small"><i class="bi bi-info-circle"></i> คำขอจะถูกส่งให้ผู้ดูแลระบบอนุมัติ</span><button class="btn btn-accent"><i class="bi bi-send"></i> ส่งคำขอลา</button></div>
</form>
<script>
document.querySelectorAll('.teacher-leave-form').forEach(form=>{const input=form.querySelector('input[type=file]');const zone=form.querySelector('.leave-dropzone');const list=form.querySelector('.leave-file-list');const render=()=>{list.innerHTML='';[...input.files].forEach(file=>{const chip=document.createElement('span');chip.className='leave-file-chip';chip.innerHTML=`<i class="bi bi-paperclip"></i><span></span><span class="text-muted">${(file.size/1048576).toFixed(1)} MB</span>`;chip.querySelector('span').textContent=file.name;list.appendChild(chip)})};input.addEventListener('change',render);['dragenter','dragover'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.add('dragover')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.remove('dragover')}));zone.addEventListener('drop',e=>{input.files=e.dataTransfer.files;render()})});
</script>
